// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDRSGPxD4YBRrgyAYNn5TzIH_4bkqCl1s',
    appId: '1:361817694015:web:13b68efee03426c151fd8a',
    messagingSenderId: '361817694015',
    projectId: 'learnroot-de5a8',
    authDomain: 'learnroot-de5a8.firebaseapp.com',
    storageBucket: 'learnroot-de5a8.firebasestorage.app',
    measurementId: 'G-7WX4DMBD5W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVkL-1_IJtxkRXOxngxlz6PqC1ARpYP6c',
    appId: '1:361817694015:android:17383d2e038c327651fd8a',
    messagingSenderId: '361817694015',
    projectId: 'learnroot-de5a8',
    storageBucket: 'learnroot-de5a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdlMxC-REBnog8OxyFY1apvs2jK1f_4u0',
    appId: '1:361817694015:ios:f98400b3ed141be251fd8a',
    messagingSenderId: '361817694015',
    projectId: 'learnroot-de5a8',
    storageBucket: 'learnroot-de5a8.firebasestorage.app',
    iosBundleId: 'com.example.learnroot71',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdlMxC-REBnog8OxyFY1apvs2jK1f_4u0',
    appId: '1:361817694015:ios:f98400b3ed141be251fd8a',
    messagingSenderId: '361817694015',
    projectId: 'learnroot-de5a8',
    storageBucket: 'learnroot-de5a8.firebasestorage.app',
    iosBundleId: 'com.example.learnroot71',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDRSGPxD4YBRrgyAYNn5TzIH_4bkqCl1s',
    appId: '1:361817694015:web:71feca3777733da151fd8a',
    messagingSenderId: '361817694015',
    projectId: 'learnroot-de5a8',
    authDomain: 'learnroot-de5a8.firebaseapp.com',
    storageBucket: 'learnroot-de5a8.firebasestorage.app',
    measurementId: 'G-CC2RTXVGYQ',
  );
}
